import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#aaa',
    marginTop: 12,
    fontSize: 14,
  },
  errorContainer: {
    flex: 1,
    backgroundColor: '#0a0a0a',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
  },
  errorText: {
    color: '#ccc',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 24,
  },
  retryButton: {
    backgroundColor: '#E50914',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 6,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 15,
  },
  backdropContainer: {
    width: '100%',
    height: 260,
    backgroundColor: '#111',
  },
  backdrop: {
    width: '100%',
    height: '100%',
  },
  backdropOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    justifyContent: 'flex-end',
  },
  backButton: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 20,
    padding: 6,
  },
  contentScroll: {
    flex: 1,
  },
  contentContainer: {
    padding: 18,
    paddingTop: 14,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  title: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
    flex: 1,
    marginRight: 12,
    letterSpacing: -0.3,
    lineHeight: 30,
  },
  favoriteButton: {
    padding: 4,
    marginTop: 2,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  metaText: {
    color: '#aaa',
    fontSize: 13,
  },
  ratingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  ratingText: {
    color: '#f5c518',
    fontSize: 13,
    fontWeight: '600',
  },
  genresRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  genreChip: {
    backgroundColor: '#1e1e1e',
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#333',
  },
  genreText: {
    color: '#ccc',
    fontSize: 12,
    fontWeight: '500',
  },
  overview: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 24,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 28,
  },
  playButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E50914',
    paddingVertical: 14,
    borderRadius: 8,
    gap: 8,
  },
  playButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 16,
  },
  myListButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1e1e1e',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: '#333',
  },
  myListButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 14,
    letterSpacing: -0.2,
  },
  castCard: {
    alignItems: 'center',
    marginRight: 14,
    width: 72,
  },
  castAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#222',
    marginBottom: 6,
  },
  castName: {
    color: '#ccc',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 15,
  },
  castCharacter: {
    color: '#666',
    fontSize: 10,
    textAlign: 'center',
  },
  similarCard: {
    marginRight: 12,
    width: 110,
  },
  similarPoster: {
    width: 110,
    height: 165,
    borderRadius: 8,
    backgroundColor: '#1a1a1a',
    marginBottom: 6,
  },
  similarTitle: {
    color: '#ccc',
    fontSize: 11,
    textAlign: 'center',
  },
  divider: {
    height: 1,
    backgroundColor: '#1e1e1e',
    marginVertical: 22,
  },
});
